### ISSUE TITLE
build not working?

### ISSUE THREAD

**Issue by abenrob** [MissingMaps/missingmaps.github.io#350]
Hey folks - pulled publish up to date in my fork, `rm -rf node_modules && npm install` then `gulp serve`

getting this:
```
[missingmaps.github.io] adam $ gulp serve
fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/adam/projects/missingmaps.github.io/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (/Users/adam/projects/missingmaps.github.io/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/Users/adam/projects/missingmaps.github.io/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/adam/projects/missingmaps.github.io/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/adam/projects/missingmaps.github.io/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/adam/projects/missingmaps.github.io/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/adam/projects/missingmaps.github.io/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

Any thoughts here? on node v6.11.2, npm 4.6.1

**Comment by dalekunce** [comment]
gotta upgrade to node v7. If you use nvm you just need to ``nvm use v7`` and then ``nom install`` and everything should be good
